spring:
  data:
    mongodb:
      host: vacancies-db
      port: 27017
      database: ${MONGO_DATABASE}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      ttl_index: 14

  rabbitmq:
    host: rabbitmq
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}


