spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: vacancies_db
      username: analytics_service
      password: password
      ttl_index: 30

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  rabbitmq:
    host: localhost
    username: analytics_service
    password: password
    port: 5672

rabbitmq:
  imported-vacancies: imported-vacancies-queue
  report-new-vacancies: new-vacancies-queue


